Soit x1 le tableau suivant :

1. Affichez la première ligne du tableau x1.

2. Affichez la deuxième colonne.

```python
x1 = np.array([[9, 1, 2],
       [8, 0, 2],
       [5, 1, 5]])
```

3. Faites la somme des lignes puis des colonnes.

4. Reprenez le tableax x1 et faite la somme de chaque colonne que vous placerez dans un tuple : (c1, c2, c3).

5. Même consigne mais maintenant pour les lignes : (l1, l2, l3).

Soit maintenant un tableau 3d 2x2x2

```python

x2 = array([ 
    [ [8, 4],[8, 9] ],
    [ [3, 0],[5, 0] ] 
])

```

6. Faites la somme selon l'axe axis = 0

7. Faites la somme selon l'axe axis = 1

8. Faites la somme selon l'axe axis = 2

9. Créez un nouveau tableau x3 de dimension 1 X 2 qui fait la somme totale de chaque ligne.

10. On voudrait sélectionner maintenant les deuxièmes valeurs dans les tableaux 2x2 de chaque ligne.

Indications : vous devriez trouver pour cette dernière question le tableau suivant :

```txt
array([[4, 9],
       [0, 0]])
```

In [4]:
import numpy as np

In [12]:
x1 = np.array([[9, 1, 2],
       [8, 0, 2],
       [5, 1, 5]])

#1
print(x1[0])

#2
print(x1[:, 1])

#3
print(x1.sum(1))
print(x1.sum(0))

#4
(c1, c2, c3) = x1.sum(0)
print(c1, c2, c3)

#5
(l1, l2, l3) = x1.sum(1)
print(l1, l2, l3)

[9 1 2]
[1 0 1]
[12 10 11]
[22  2  9]
22 2 9
12 10 11


In [16]:
x2 = np.array([ 
    [ [8, 4],[8, 9] ],
    [ [3, 0],[5, 0] ] 
])

#6
print(x2.sum(0))

#7
print(x2.sum(1))

#8
print(x2.sum(2))

#9


#10
print(x2[:, :, 1])

[[11  4]
 [13  9]]
[[16 13]
 [ 8  0]]
[[12 17]
 [ 3  5]]
[[4 9]
 [0 0]]
