Soit le tableau suivant modifiez les lignes suivantes :

1. Dans une copie , une ligne sur 2 multipliez toutes les valeurs par 2.

2. Dans une copie, une ligne sur 3 multipliez toutes les valeurs par 3.

3. Ajoutez 100 à la dernière valeur de chaque ligne.

```python

y1 = np.array([[5, 5, 1, 6, 5],
       [7, 7, 8, 9, 6],
       [1, 7, 2, 4, 5],
       [3, 4, 7, 0, 8],
       [1, 8, 2, 0, 2]])


yy1 = np.copy(y1, copy=True)
```

Soit maintenant le tableau de dimension 5x5x5 suivant, répondez aux questions ci-dessous :

4. Pour chaque "numéro" de matrice paire et chaque ligne paire multipliez par 2 les valeurs.

5. Pour chaque matrice dont la somme des valeurs de la ligne est impaire, ajoutez 100 à toutes les valeurs de cette ligne.

6. Reprenez la matrice initiale y2 et ajoutez 1000 à la dernière valeur de chaque ligne de chaque matrice.

7. Pour chaque matrice dont la somme totale des valeurs est impaire, ajoutez 100 à toutes les valeurs de cette matrice.

```python

y2 = np.array([[[89, 26, 78, 55, 23],
        [32, 92, 86, 55, 27],
        [87, 46, 63, 43, 77],
        [27, 18, 15, 20, 65],
        [52, 75, 82,  9, 38]],

       [[78, 20, 86, 16, 31],
        [46,  3, 59,  6, 50],
        [76, 73, 41, 66, 42],
        [70, 80, 62, 58, 41],
        [41, 65, 49,  0, 79]],

       [[13,  9, 58, 35, 32],
        [80, 86, 30, 73, 18],
        [52, 73, 74,  8, 40],
        [80, 27, 26, 94,  8],
        [30, 62,  3, 35, 75]],

       [[69, 54, 24, 28, 44],
        [29, 85, 56,  7, 69],
        [13,  1, 62, 10, 66],
        [ 6,  5, 31, 78, 92],
        [11, 41, 38,  4, 67]],

       [[30, 91, 12, 10, 91],
        [65, 95, 36, 54, 35],
        [49, 96, 21,  5, 87],
        [68, 82, 90, 36, 56],
        [41, 18, 75, 39, 99]]])
```


In [1]:
import numpy as np

In [11]:
y1 = np.array([[5, 5, 1, 6, 5],
       [7, 7, 8, 9, 6],
       [1, 7, 2, 4, 5],
       [3, 4, 7, 0, 8],
       [1, 8, 2, 0, 2]])

yy1 = np.copy(y1)
yy2 = np.copy(y1)
yy3 = np.copy(y1)

#1
yy1[::2] = yy1[::2]*2

#2
yy2[::3] = yy2[::3]*3

#3
yy3[:, -1] = yy3[:, -1] + 100

print(yy3)

[[  5   5   1   6 105]
 [  7   7   8   9 106]
 [  1   7   2   4 105]
 [  3   4   7   0 108]
 [  1   8   2   0 102]]


In [18]:
y2 = np.array([[[89, 26, 78, 55, 23],
        [32, 92, 86, 55, 27],
        [87, 46, 63, 43, 77],
        [27, 18, 15, 20, 65],
        [52, 75, 82,  9, 38]],

       [[78, 20, 86, 16, 31],
        [46,  3, 59,  6, 50],
        [76, 73, 41, 66, 42],
        [70, 80, 62, 58, 41],
        [41, 65, 49,  0, 79]],

       [[13,  9, 58, 35, 32],
        [80, 86, 30, 73, 18],
        [52, 73, 74,  8, 40],
        [80, 27, 26, 94,  8],
        [30, 62,  3, 35, 75]],

       [[69, 54, 24, 28, 44],
        [29, 85, 56,  7, 69],
        [13,  1, 62, 10, 66],
        [ 6,  5, 31, 78, 92],
        [11, 41, 38,  4, 67]],

       [[30, 91, 12, 10, 91],
        [65, 95, 36, 54, 35],
        [49, 96, 21,  5, 87],
        [68, 82, 90, 36, 56],
        [41, 18, 75, 39, 99]]])

mask = y2.sum(2) % 2 != 0

y2[mask, :] + 100

array([[189, 126, 178, 155, 123],
       [127, 118, 115, 120, 165],
       [178, 120, 186, 116, 131],
       [170, 180, 162, 158, 141],
       [113, 109, 158, 135, 132],
       [180, 186, 130, 173, 118],
       [152, 173, 174, 108, 140],
       [180, 127, 126, 194, 108],
       [130, 162, 103, 135, 175],
       [169, 154, 124, 128, 144],
       [111, 141, 138, 104, 167],
       [165, 195, 136, 154, 135]])